ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_network_os: dellemc.enterprise_sonic.sonic
ansible_password: admin
ansible_user: admin
bgp_asn: '{{ host_data[inventory_hostname].bgp_asn }}'
bgp_router_id: '{{ host_data[inventory_hostname].bgp_router_id }}'
host_data:
  NewFabric-LEAF-1:
    bgp_asn: 64602
    bgp_router_id: 10.1.2.1
    loopback0_ip: 10.1.2.1/32
    loopback1_ip: 1.1.1.1/32
    mclag_peer_ip: 10.1.2.2
    mgmt_gateway_ip: 10.10.20.254
    mgmt_ip: 10.10.20.12/24
    vtep_name: vtep1
  NewFabric-LEAF-2:
    bgp_asn: 64602
    bgp_router_id: 10.1.2.2
    loopback0_ip: 10.1.2.2/32
    loopback1_ip: 1.1.1.1/32
    mclag_peer_ip: 10.1.2.1
    mgmt_gateway_ip: 10.10.20.254
    mgmt_ip: 10.10.20.13/24
    vtep_name: vtep1
  NewFabric-LEAF-3:
    bgp_asn: 64603
    bgp_router_id: 10.1.2.3
    loopback0_ip: 10.1.2.3/32
    loopback1_ip: 1.1.1.2/32
    mclag_peer_ip: 10.1.2.4
    mgmt_gateway_ip: 10.10.20.254
    mgmt_ip: 10.10.20.14/24
    vtep_name: vtep3
  NewFabric-LEAF-4:
    bgp_asn: 64603
    bgp_router_id: 10.1.2.4
    loopback0_ip: 10.1.2.4/32
    loopback1_ip: 1.1.1.2/32
    mclag_peer_ip: 10.1.2.3
    mgmt_gateway_ip: 10.10.20.254
    mgmt_ip: 10.10.20.15/24
    vtep_name: vtep3
  NewFabric-SPINE-1:
    bgp_asn: 64601
    bgp_router_id: 10.1.1.1
    loopback0_ip: 10.1.1.1/32
    mgmt_gateway_ip: 10.10.20.254
    mgmt_ip: 10.10.20.10/24
  NewFabric-SPINE-2:
    bgp_asn: 64601
    bgp_router_id: 10.1.1.2
    loopback0_ip: 10.1.1.2/32
    mgmt_gateway_ip: 10.10.20.254
    mgmt_ip: 10.10.20.11/24
loopback0_ip: '{{ host_data[inventory_hostname].loopback0_ip }}'
loopback_inf0: Loopback0
loopback_inf1: Loopback1
mgmt_gateway_ip: '{{ host_data[inventory_hostname].mgmt_gateway_ip }}'
mgmt_ip: '{{ host_data[inventory_hostname].mgmt_ip }}'
sonic_bgp_fabriclink_neighbors_aflist:
  - activate: true
    afi: ipv4
    allowas_in:
      value: 2
    safi: unicast
  - activate: true
    afi: l2vpn
    safi: evpn
sonic_bgp_spineleaf_peergroup:
  advertisement_interval: 5
  bfd:
    enabled: true
  capability:
    extended_nexthop: true
  name: spine-leaf
  remote_as:
    peer_type: external
  timers:
    holdtime: 9
    keepalive: 3
vlan_info: {}
