sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 16
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{bgp_asn}}'
