is_border_leaf: true
lacp_pcs: []
mclag_member_pcs: []
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: Vrf1
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 16
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
    bgp_as: '{{bgp_asn}}'
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/54
        peer_group: spine-leaf
      - neighbor: Eth1/53
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/54
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/53
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"Uplink"'
    enabled: true
    name: Eth1/1
  - description: '"Uplink"'
    enabled: true
    name: Eth1/2
  - description: '"Uplink to NewFabric-SPINE-2 Eth1/1/1"'
    enabled: true
    name: Eth1/53
  - description: '"Uplink to NewFabric-SPINE-1 Eth1/1/1"'
    enabled: true
    name: Eth1/54
  - description: '"MCLAG to NewFabric-LEAF-2 Eth1/55"'
    enabled: true
    name: Eth1/55
  - description: '"MCLAG to NewFabric-LEAF-2 Eth1/56"'
    enabled: true
    name: Eth1/56
  - description: router-id
    name: '{{ loopback_inf0 }}'
  - description: vtep
    name: '{{ loopback_inf1 }}'
sonic_l2_interfaces:
  - name: Eth1/1
    trunk:
      allowed_vlans:
        - vlan: 200
  - name: Eth1/2
    trunk:
      allowed_vlans:
        - vlan: 200
sonic_l3_interfaces:
  - ipv6:
      enabled: true
    name: Eth1/53
  - ipv6:
      enabled: true
    name: Eth1/54
  - ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
    name: '{{ loopback_inf0 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
    name: '{{ loopback_inf1 }}'
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/55
        - member: Eth1/56
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: NewFabric-LEAF-1
  interface_naming: standard
sonic_vlans:
  - vlan_id: 200
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan200
    name: Vrf1
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep1
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map: []
    vrf_map: []
vlans: []
vrfs: []
